
stages:
  - build

cache:
  key: single-cache
  paths:
    - .multirust
    - .cargo

compile-windows:
  stage: build
  tags:
    - windows
  script:
    - node release\ci-compile.js windows
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

compile-darwin:
  stage: build
  tags:
    - darwin
  script:
    - release/ci-compile.js darwin
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

compile-linux-386:
  stage: build
  tags:
    - docker-capsule-32
  script:
    - release/ci-compile.js linux 386
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week

compile-linux-amd64:
  stage: build
  tags:
    - docker-capsule-64
  script:
    - release/ci-compile.js linux amd64
  artifacts:
    paths:
      - compile-artifacts
    expire_in: 1 week
