[package]
name = "hook"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
# hook any function, like glXSwapBuffers, etc.
detour = { version = "0.6.0", default-features = false }